services:
  - type: web
    name: HealthCoverAI-2
    env: python
    plan: free
    buildCommand: |
      python -V
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python-3.10.13
